package es.upm.dit.isst.inube.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class TestGestionCuenta {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	
	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\luisg\\Downloads\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	
	@After
	public void tearDown() {
		driver.quit();
	}
	
	@Test
	public void testGestionCuenta() {
		driver.get("http://localhost:8080/INUBE/");
		driver.manage().window().setSize(new Dimension(1936, 1056));
		driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
		driver.findElement(By.name("usuario")).sendKeys("selenium");
		driver.findElement(By.name("password1")).sendKeys("selenium");
		driver.findElement(By.cssSelector(".btn-block")).click();
		driver.findElement(By.name("usuario")).click();
		driver.findElement(By.name("usuario")).sendKeys("selenium");
		driver.findElement(By.name("password")).sendKeys("selenium");
		driver.findElement(By.cssSelector(".btn-block")).click();
		driver.findElement(By.linkText("Home")).click();
		assertThat(driver.findElement(By.cssSelector(".mt-3")).getText(), is("¡Hola selenium, bienvenido a iNube!"));
		driver.findElement(By.linkText("Gestiona tu cuenta")).click();
		assertThat(driver.findElement(By.cssSelector(".col-md-12 > .mb-3:nth-child(3)")).getText(), is("No tienes comercios"));
		
		// crear comercio
		driver.findElement(By.name("merchantId")).click();
		driver.findElement(By.name("merchantId")).sendKeys("25804932");
		driver.findElement(By.name("nombreComercio")).click();
		driver.findElement(By.name("nombreComercio")).sendKeys("Prueba");
		driver.findElement(By.name("sector")).click();
		{
			WebElement dropdown = driver.findElement(By.name("sector"));
			dropdown.findElement(By.xpath("//option[. = 'Informática']")).click();
		}
		driver.findElement(By.name("sector")).click();
		driver.findElement(By.name("cp")).click();
		driver.findElement(By.name("cp")).sendKeys("87061");
		driver.findElement(By.name("banco")).click();
		driver.findElement(By.name("banco")).sendKeys("Popular");
		driver.findElement(By.cssSelector(".btn-block")).click();
		
		// comprobar datos comercio creado
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(1)")).getText(), is("25804932"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(2)")).getText(), is("Prueba"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(3)")).getText(), is("Informatica"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(4)")).getText(), is("87061"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(5)")).getText(), is("Popular"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(6)")).getText(), is("0"));
		
		// modificar comercio
		driver.findElement(By.cssSelector(".btn-outline-primary")).click();
		driver.findElement(By.name("nombreComercio")).clear();
		driver.findElement(By.name("nombreComercio")).sendKeys("Prueba modificado");
		driver.findElement(By.name("sector")).click();
		{
			WebElement dropdown = driver.findElement(By.name("sector"));
			dropdown.findElement(By.xpath("//option[. = 'Carnicería']")).click();
		}
		driver.findElement(By.name("sector")).click();
		driver.findElement(By.name("cp")).clear();
		driver.findElement(By.name("cp")).sendKeys("16087");
		driver.findElement(By.name("banco")).clear();
		driver.findElement(By.name("banco")).sendKeys("Caja Madrid");
		driver.findElement(By.cssSelector(".btn-block")).click();
		
		// comprobar datos comercio modificado
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(1)")).getText(), is("25804932"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(2)")).getText(), is("Prueba modificado"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(3)")).getText(), is("Carniceria"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(4)")).getText(), is("16087"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(5)")).getText(), is("Caja Madrid"));
		assertThat(driver.findElement(By.cssSelector(".align-middle:nth-child(6)")).getText(), is("0"));
	}
}
