package es.upm.dit.isst.inube.test;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class TestEstadisticasComparadas {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	
	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\luisg\\Downloads\\chromedriver.exe");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	
	@After
	public void tearDown() {
		driver.quit();
	}
	
	@Test
	public void testEstadisticasComparadas() {
		driver.get("http://localhost:8080/INUBE/");
		driver.manage().window().setSize(new Dimension(1904, 1031));
		driver.findElement(By.name("usuario")).sendKeys("eduardoG");
		driver.findElement(By.name("password")).sendKeys("eduardo");
		driver.findElement(By.cssSelector(".btn-block")).click();
		
		driver.findElement(By.cssSelector("form:nth-child(6) > .btn")).click();
		driver.findElement(By.cssSelector("tr:nth-child(1) .btn")).click();
		
		assertThat(driver.findElement(By.cssSelector(".table:nth-child(4) .align-middle:nth-child(1)")).getText(), is("15592835"));
		assertThat(driver.findElement(By.cssSelector(".table:nth-child(4) .align-middle:nth-child(2)")).getText(), is("beauty max"));
		assertThat(driver.findElement(By.cssSelector(".table:nth-child(4) .align-middle:nth-child(3)")).getText(), is("Estetica"));
		assertThat(driver.findElement(By.cssSelector(".table:nth-child(4) .align-middle:nth-child(4)")).getText(), is("28001"));
		assertThat(driver.findElement(By.cssSelector(".table:nth-child(4) .align-middle:nth-child(5)")).getText(), is("Santander"));
		
		assertThat(driver.findElement(By.cssSelector(".table:nth-child(5) .align-middle:nth-child(1)")).getText(), is("56"));
		assertThat(driver.findElement(By.cssSelector(".table:nth-child(5) .align-middle:nth-child(2)")).getText(), is("2006€"));
		assertThat(driver.findElement(By.cssSelector(".table:nth-child(5) .align-middle:nth-child(3)")).getText(), is("24"));
		assertThat(driver.findElement(By.cssSelector(".table:nth-child(5) .align-middle:nth-child(4)")).getText(), is("35,83€"));
		assertThat(driver.findElement(By.cssSelector(".col-md-2 .align-middle")).getText(), is("33,47€"));
	}
}
